// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DailyActivitySummary.Dal;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DailyActivitySummary.Dal.Configurations
{
    public partial class ContactInfoContactLogsConfiguration : IEntityTypeConfiguration<ContactInfoContactLogs>
    {
        public void Configure(EntityTypeBuilder<ContactInfoContactLogs> entity)
        {
            entity.HasKey(e => new { e.ContactInfoContactId, e.ContactLogContactLogId })
                .HasName("PK_dbo.ContactInfoContactLogs");

            entity.HasOne(d => d.ContactInfoContact)
                .WithMany(p => p.ContactInfoContactLogs)
                .HasForeignKey(d => d.ContactInfoContactId)
                .HasConstraintName("FK_dbo.ContactInfoContactLogs_ROWM.ContactInfo_ContactInfo_ContactId");

            entity.HasOne(d => d.ContactLogContactLog)
                .WithMany(p => p.ContactInfoContactLogs)
                .HasForeignKey(d => d.ContactLogContactLogId)
                .HasConstraintName("FK_dbo.ContactInfoContactLogs_ROWM.ContactLog_ContactLog_ContactLogId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactInfoContactLogs> entity);
    }
}
