// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DailyActivitySummary.Dal;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DailyActivitySummary.Dal.Configurations
{
    public partial class ParcelDocumentsConfiguration : IEntityTypeConfiguration<ParcelDocuments>
    {
        public void Configure(EntityTypeBuilder<ParcelDocuments> entity)
        {
            entity.HasKey(e => new { e.ParcelParcelId, e.DocumentDocumentId })
                .HasName("PK_dbo.ParcelDocuments");

            entity.HasOne(d => d.DocumentDocument)
                .WithMany(p => p.ParcelDocuments)
                .HasForeignKey(d => d.DocumentDocumentId)
                .HasConstraintName("FK_dbo.ParcelDocuments_ROWM.Document_Document_DocumentId");

            entity.HasOne(d => d.ParcelParcel)
                .WithMany(p => p.ParcelDocuments)
                .HasForeignKey(d => d.ParcelParcelId)
                .HasConstraintName("FK_dbo.ParcelDocuments_ROWM.Parcel_Parcel_ParcelId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelDocuments> entity);
    }
}
