// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DailyActivitySummary.Dal;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DailyActivitySummary.Dal.Configurations
{
    public partial class ParcelStatusConfiguration : IEntityTypeConfiguration<ParcelStatus>
    {
        public void Configure(EntityTypeBuilder<ParcelStatus> entity)
        {
            entity.Property(e => e.Code).IsUnicode(false);

            entity.Property(e => e.Category).IsUnicode(false);

            entity.Property(e => e.ParentStatusCode).IsUnicode(false);

            entity.HasOne(d => d.CategoryNavigation)
                .WithMany(p => p.ParcelStatus)
                .HasForeignKey(d => d.Category)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Parcel_Status_Category");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelStatus> entity);
    }
}
