// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DailyActivitySummary.Dal;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DailyActivitySummary.Dal.Configurations
{
    public partial class ParcelConfiguration : IEntityTypeConfiguration<Parcel>
    {
        public void Configure(EntityTypeBuilder<Parcel> entity)
        {
            entity.Property(e => e.ParcelId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.ClearanceCode).IsUnicode(false);

            entity.Property(e => e.CountyFips)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.FinalEasementOfferOfferAmount).HasDefaultValueSql("((0))");

            entity.Property(e => e.FinalEasementOfferOfferDate).HasDefaultValueSql("('0001-01-01T00:00:00.000+00:00')");

            entity.Property(e => e.FinalOptionOfferOfferAmount).HasDefaultValueSql("((0))");

            entity.Property(e => e.FinalOptionOfferOfferDate).HasDefaultValueSql("('0001-01-01T00:00:00.000+00:00')");

            entity.Property(e => e.FinalRoeofferOfferAmount).HasDefaultValueSql("((0))");

            entity.Property(e => e.FinalRoeofferOfferDate).HasDefaultValueSql("('0001-01-01T00:00:00.000+00:00')");

            entity.Property(e => e.InitialEasementOfferOfferAmount).HasDefaultValueSql("((0))");

            entity.Property(e => e.InitialEasementOfferOfferDate).HasDefaultValueSql("('0001-01-01T00:00:00.000+00:00')");

            entity.Property(e => e.InitialOptionOfferOfferAmount).HasDefaultValueSql("((0))");

            entity.Property(e => e.InitialOptionOfferOfferDate).HasDefaultValueSql("('0001-01-01T00:00:00.000+00:00')");

            entity.Property(e => e.InitialRoeofferOfferAmount).HasDefaultValueSql("((0))");

            entity.Property(e => e.InitialRoeofferOfferDate).HasDefaultValueSql("('0001-01-01T00:00:00.000+00:00')");

            entity.Property(e => e.ParcelStatusCode).IsUnicode(false);

            entity.Property(e => e.RoeStatusCode).IsUnicode(false);

            entity.HasOne(d => d.ClearanceCodeNavigation)
                .WithMany(p => p.ParcelClearanceCodeNavigation)
                .HasForeignKey(d => d.ClearanceCode)
                .HasConstraintName("FK_Clearance_Status");

            entity.HasOne(d => d.ParcelStatusCodeNavigation)
                .WithMany(p => p.ParcelParcelStatusCodeNavigation)
                .HasForeignKey(d => d.ParcelStatusCode)
                .HasConstraintName("FK_Acquisition_Status");

            entity.HasOne(d => d.RoeStatusCodeNavigation)
                .WithMany(p => p.ParcelRoeStatusCodeNavigation)
                .HasForeignKey(d => d.RoeStatusCode)
                .HasConstraintName("FK_Roe_Status");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Parcel> entity);
    }
}
