// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DailyActivitySummary.Dal;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DailyActivitySummary.Dal.Configurations
{
    public partial class ParcelContactLogsConfiguration : IEntityTypeConfiguration<ParcelContactLogs>
    {
        public void Configure(EntityTypeBuilder<ParcelContactLogs> entity)
        {
            entity.HasKey(e => new { e.ParcelParcelId, e.ContactLogContactLogId })
                .HasName("PK_dbo.ParcelContactLogs");

            entity.HasOne(d => d.ContactLogContactLog)
                .WithMany(p => p.ParcelContactLogs)
                .HasForeignKey(d => d.ContactLogContactLogId)
                .HasConstraintName("FK_dbo.ParcelContactLogs_ROWM.ContactLog_ContactLog_ContactLogId");

            entity.HasOne(d => d.ParcelParcel)
                .WithMany(p => p.ParcelContactLogs)
                .HasForeignKey(d => d.ParcelParcelId)
                .HasConstraintName("FK_dbo.ParcelContactLogs_ROWM.Parcel_Parcel_ParcelId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelContactLogs> entity);
    }
}
