//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action_Item()
        {
            this.Action_Item_Activity = new HashSet<Action_Item_Activity>();
        }
    
        public System.Guid ActionItemId { get; set; }
        public Nullable<System.Guid> ParcelId { get; set; }
        public Nullable<System.Guid> AssignedGroupId { get; set; }
        public Nullable<System.Guid> ActivityId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTimeOffset> DueDate { get; set; }
        public int Status { get; set; }
        public System.DateTimeOffset Created { get; set; } = DateTimeOffset.UtcNow;
        public System.DateTimeOffset LastModified { get; set; } = DateTimeOffset.UtcNow;
        public string ModifiedBy { get; set; } = "";
    
        public virtual Status_Activity Status_Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Item_Activity> Action_Item_Activity { get; set; }
        public virtual Action_Item_Group Action_Item_Group { get; set; }
        public virtual Parcel Parcel { get; set; }
    }

    public enum ActionStatus { Pending = 1, Started, Completed, Canceled }
}
