//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action_Item_Activity
    {
        public System.Guid ActivityId { get; set; }
        public System.Guid ActionItemId { get; set; }
        public string Action { get; set; }
        public string OriginalAction { get; set; }
        public int Status { get; set; }
        public Nullable<int> OriginalStatus { get; set; }
        public Nullable<System.DateTimeOffset> DueDate { get; set; }
        public Nullable<System.DateTimeOffset> OriginalDueDate { get; set; }
        public System.Guid Assigned { get; set; }
        public Nullable<System.Guid> OriginalAssigned { get; set; }
        public Nullable<System.Guid> UpdateAgentId { get; set; }
        public System.DateTimeOffset ActivityDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Action_Item Action_Item { get; set; }

        public virtual Agent UpdateAgent { get; set; }
    }
}
