//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action_Item_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action_Item_Group()
        {
            this.Action_Item = new HashSet<Action_Item>();
            this.Action_Item_Group_Member = new HashSet<Action_Item_Group_Member>();
        }
    
        public System.Guid ActionItemGroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupNameCaption { get; set; }
        public string Company { get; set; }
        public bool CanCreateItem { get; set; }
        public bool CanPerformItem { get; set; }
        public bool CanCloseItem { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Item> Action_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Item_Group_Member> Action_Item_Group_Member { get; set; }
    }
}
