//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action_Item_Group_Member
    {
        public System.Guid ActionGroupMemberId { get; set; }
        public System.Guid ParentGroupId { get; set; }
        public string MemberName { get; set; }
        public string Email { get; set; }
        public string MessageNumber { get; set; }
        public bool IsSend { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Action_Item_Group Action_Item_Group { get; set; }
    }
}
