//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public System.Guid ID { get; set; }
        public string Caption { get; set; }
        public int LayerType { get; set; }
        public string AgsUrl { get; set; }
        public string LayerId { get; set; }
        public int DisplayOrder { get; set; }
    }
}
