//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Part()
        {
            this.Map = new HashSet<Map>();
            this.Parcel_Allocation = new HashSet<Parcel_Allocation>();
        }
    
        public int ProjectPartId { get; set; }
        public string Caption { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<System.DateTimeOffset> ScheduleStart { get; set; }
        public Nullable<System.DateTimeOffset> ScheduleCompletion { get; set; }
        public Nullable<System.DateTimeOffset> ActualStart { get; set; }
        public Nullable<System.DateTimeOffset> ActualCompletion { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map> Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcel_Allocation> Parcel_Allocation { get; set; }
    }
}
