//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoeConditions
    {
        public System.Guid ConditionId { get; set; }
        public string Condition { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTimeOffset> EffectiveStartDate { get; set; }
        public Nullable<System.DateTimeOffset> EffectiveEndDate { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.Guid> Parcel_ParcelId { get; set; }
        public Nullable<System.Guid> Contact { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual Parcel Parcel { get; set; }
    }
}
