//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status_Activity()
        {
            this.Action_Item = new HashSet<Action_Item>();
        }
    
        public System.Guid ActivityId { get; set; }
        public System.DateTimeOffset ActivityDate { get; set; }
        public System.Guid ParentParcelId { get; set; }
        public System.Guid AgentId { get; set; }
        public string StatusCode { get; set; }
        public string OriginalStatusCode { get; set; }
        public string Notes { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Parcel Parcel { get; set; }
        public virtual Parcel_Status Parcel_Status { get; set; }
        public virtual Parcel_Status Parcel_Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Item> Action_Item { get; set; }
    }
}
