// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DailyActivitySummary.Dal
{
    [Table("Agent", Schema = "ROWM")]
    public partial class Agent
    {
        [Key]
        public Guid AgentId { get; set; }
        [Required]
        [StringLength(20)]
        public string AgentName { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty("ContactAgent")]
        public virtual ICollection<ContactLog> ContactLog { get; set; }
        [InverseProperty("Agent")]
        public virtual ICollection<DocumentActivity> DocumentActivity { get; set; }
        [InverseProperty("Agent")]
        public virtual ICollection<StatusActivity> StatusActivity { get; set; }
    }
}