// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DailyActivitySummary.Dal.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace DailyActivitySummary.Dal
{
    public partial class DailySummaryContext : DbContext
    {
        public DailySummaryContext()
        {
        }

        public DailySummaryContext(DbContextOptions<DailySummaryContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<ContactInfoContactLogs> ContactInfoContactLogs { get; set; }
        public virtual DbSet<ContactLog> ContactLog { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentActivity> DocumentActivity { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Ownership> Ownership { get; set; }
        public virtual DbSet<Parcel> Parcel { get; set; }
        public virtual DbSet<ParcelContactLogs> ParcelContactLogs { get; set; }
        public virtual DbSet<ParcelDocuments> ParcelDocuments { get; set; }
        public virtual DbSet<ParcelStatus> ParcelStatus { get; set; }
        public virtual DbSet<StatusActivity> StatusActivity { get; set; }
        public virtual DbSet<StatusCategory> StatusCategory { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new AgentConfiguration());
            modelBuilder.ApplyConfiguration(new ContactInfoConfiguration());
            modelBuilder.ApplyConfiguration(new ContactInfoContactLogsConfiguration());
            modelBuilder.ApplyConfiguration(new ContactLogConfiguration());
            modelBuilder.ApplyConfiguration(new DocumentConfiguration());
            modelBuilder.ApplyConfiguration(new DocumentActivityConfiguration());
            modelBuilder.ApplyConfiguration(new OwnerConfiguration());
            modelBuilder.ApplyConfiguration(new OwnershipConfiguration());
            modelBuilder.ApplyConfiguration(new ParcelConfiguration());
            modelBuilder.ApplyConfiguration(new ParcelContactLogsConfiguration());
            modelBuilder.ApplyConfiguration(new ParcelDocumentsConfiguration());
            modelBuilder.ApplyConfiguration(new ParcelStatusConfiguration());
            modelBuilder.ApplyConfiguration(new StatusActivityConfiguration());
            modelBuilder.ApplyConfiguration(new StatusCategoryConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
