// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DailyActivitySummary.Dal
{
    [Table("ContactInfo", Schema = "ROWM")]
    public partial class ContactInfo
    {
        [Key]
        public Guid ContactId { get; set; }
        public bool IsPrimaryContact { get; set; }
        [StringLength(50)]
        public string OwnerFirstName { get; set; }
        [StringLength(50)]
        public string OwnerLastName { get; set; }
        [StringLength(400)]
        public string OwnerStreetAddress { get; set; }
        [StringLength(100)]
        public string OwnerCity { get; set; }
        [StringLength(20)]
        public string OwnerState { get; set; }
        [Column("OwnerZIP")]
        [StringLength(10)]
        public string OwnerZip { get; set; }
        [StringLength(256)]
        public string OwnerEmail { get; set; }
        public string OwnerHomePhone { get; set; }
        public string OwnerCellPhone { get; set; }
        public string OwnerWorkPhone { get; set; }
        public Guid ContactOwnerId { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [Required]
        [StringLength(20)]
        public string Representation { get; set; }

        [ForeignKey(nameof(ContactOwnerId))]
        [InverseProperty(nameof(Owner.ContactInfo))]
        public virtual Owner ContactOwner { get; set; }
        [InverseProperty("ContactInfoContact")]
        public virtual ICollection<ContactInfoContactLogs> ContactInfoContactLogs { get; set; }
    }
}