// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DailyActivitySummary.Dal
{
    [Table("Owner", Schema = "ROWM")]
    public partial class Owner
    {
        [Key]
        public Guid OwnerId { get; set; }
        [StringLength(200)]
        public string PartyName { get; set; }
        [StringLength(50)]
        public string OwnerType { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [InverseProperty("ContactOwner")]
        public virtual ICollection<ContactInfo> ContactInfo { get; set; }
        [InverseProperty("OwnerOwner")]
        public virtual ICollection<ContactLog> ContactLog { get; set; }
        [InverseProperty("Owner")]
        public virtual ICollection<Ownership> Ownership { get; set; }
    }
}