// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DailyActivitySummary.Dal
{
    [Table("Parcel", Schema = "ROWM")]
    public partial class Parcel
    {
        [Key]
        public Guid ParcelId { get; set; }
        [Required]
        [Column("Assessor_Parcel_Number")]
        [StringLength(128)]
        public string AssessorParcelNumber { get; set; }
        [Column("Tracking_Number")]
        public string TrackingNumber { get; set; }
        [Required]
        [Column("County_FIPS")]
        [StringLength(5)]
        public string CountyFips { get; set; }
        [Column("County_Name")]
        [StringLength(50)]
        public string CountyName { get; set; }
        [StringLength(800)]
        public string SitusAddress { get; set; }
        public double? Acreage { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [Column("InitialROEOffer_OfferDate")]
        public DateTimeOffset? InitialRoeofferOfferDate { get; set; }
        [Column("InitialROEOffer_OfferAmount")]
        public double? InitialRoeofferOfferAmount { get; set; }
        [Column("InitialROEOffer_OfferNotes")]
        public string InitialRoeofferOfferNotes { get; set; }
        [Column("FinalROEOffer_OfferDate")]
        public DateTimeOffset? FinalRoeofferOfferDate { get; set; }
        [Column("FinalROEOffer_OfferAmount")]
        public double? FinalRoeofferOfferAmount { get; set; }
        [Column("FinalROEOffer_OfferNotes")]
        public string FinalRoeofferOfferNotes { get; set; }
        [Column("InitialOptionOffer_OfferDate")]
        public DateTimeOffset? InitialOptionOfferOfferDate { get; set; }
        [Column("InitialOptionOffer_OfferAmount")]
        public double? InitialOptionOfferOfferAmount { get; set; }
        [Column("InitialOptionOffer_OfferNotes")]
        public string InitialOptionOfferOfferNotes { get; set; }
        [Column("FinalOptionOffer_OfferDate")]
        public DateTimeOffset? FinalOptionOfferOfferDate { get; set; }
        [Column("FinalOptionOffer_OfferAmount")]
        public double? FinalOptionOfferOfferAmount { get; set; }
        [Column("FinalOptionOffer_OfferNotes")]
        public string FinalOptionOfferOfferNotes { get; set; }
        [Column("InitialEasementOffer_OfferDate")]
        public DateTimeOffset? InitialEasementOfferOfferDate { get; set; }
        [Column("InitialEasementOffer_OfferAmount")]
        public double? InitialEasementOfferOfferAmount { get; set; }
        [Column("InitialEasementOffer_OfferNotes")]
        public string InitialEasementOfferOfferNotes { get; set; }
        [Column("FinalEasementOffer_OfferDate")]
        public DateTimeOffset? FinalEasementOfferOfferDate { get; set; }
        [Column("FinalEasementOffer_OfferAmount")]
        public double? FinalEasementOfferOfferAmount { get; set; }
        [Column("FinalEasementOffer_OfferNotes")]
        public string FinalEasementOfferOfferNotes { get; set; }
        [StringLength(50)]
        public string ParcelStatusCode { get; set; }
        [StringLength(50)]
        public string RoeStatusCode { get; set; }
        public bool IsActive { get; set; }
        [Column("Landowner_Score")]
        public int? LandownerScore { get; set; }
        [StringLength(50)]
        public string ClearanceCode { get; set; }

        [ForeignKey(nameof(ClearanceCode))]
        [InverseProperty(nameof(ParcelStatus.ParcelClearanceCodeNavigation))]
        public virtual ParcelStatus ClearanceCodeNavigation { get; set; }
        [ForeignKey(nameof(ParcelStatusCode))]
        [InverseProperty(nameof(ParcelStatus.ParcelParcelStatusCodeNavigation))]
        public virtual ParcelStatus ParcelStatusCodeNavigation { get; set; }
        [ForeignKey(nameof(RoeStatusCode))]
        [InverseProperty(nameof(ParcelStatus.ParcelRoeStatusCodeNavigation))]
        public virtual ParcelStatus RoeStatusCodeNavigation { get; set; }
        [InverseProperty("Parcel")]
        public virtual ICollection<Ownership> Ownership { get; set; }
        [InverseProperty("ParcelParcel")]
        public virtual ICollection<ParcelContactLogs> ParcelContactLogs { get; set; }
        [InverseProperty("ParcelParcel")]
        public virtual ICollection<ParcelDocuments> ParcelDocuments { get; set; }
    }
}