// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DailyActivitySummary.Dal
{
    [Table("Status_Activity", Schema = "ROWM")]
    public partial class StatusActivity
    {
        [Key]
        public Guid ActivityId { get; set; }
        public DateTimeOffset ActivityDate { get; set; }
        public Guid ParentParcelId { get; set; }
        public Guid AgentId { get; set; }
        [Required]
        [StringLength(50)]
        public string StatusCode { get; set; }
        [StringLength(50)]
        public string OriginalStatusCode { get; set; }
        public string Notes { get; set; }

        [ForeignKey(nameof(AgentId))]
        [InverseProperty("StatusActivity")]
        public virtual Agent Agent { get; set; }
    }
}